AGENT_COUNT = 2
WAIT_UNTIL_ALL_AGENTS_TERMINATED = [True, False]  # [train, test]
DEATH_HANDLING = "DEATH_MASKING"  # "STOP_ADDING", "DEATH_MASKING"
TEAM_SPIRIT = [False, 0.3, 0.3]  # Use Team
SHARED_REPLAY_BUFFER = False
PARAMETER_SHARING = ["NONE", "ONE_UPDATE"]  # [(NONE, FULL, PARTIAL), (EACH_UPDATE, ONE_UPDATE)]
